{% set name = "pyfiglet" %}
{% set version = "0.8.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6c2321755d09267b438ec7b936825a4910fec696292139e664ca8670e103639

build:
  number: 0
  entry_points:
    - pyfiglet = pyfiglet:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pyfiglet
    - pyfiglet.fonts
  commands:
    - pip check
    - pyfiglet --help
  requires:
    - pip

about:
  home: https://github.com/pwaller/pyfiglet
  summary: 'Pure-python FIGlet implementation'
  license_file: LICENSE
  license: MIT
  license_family: MIT
  dev_url: https://github.com/pwaller/pyfiglet
  doc_url: https://github.com/pwaller/pyfiglet/blob/main/README.md
  description: pyfiglet is a full port of FIGlet (http://www.figlet.org/) into pure python.

extra:
  recipe-maintainers:
    - pmlandwehr
