# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JLr3R47S1l3WREPzB0QN2wSzvDKNpl9n9cuksz4TVfjkdUW6UcM0d3wg3kEUJTvL9OmW1t690THIbN593yAXbDWryzR8pYNGzPJXTzKKKaVbxcu8esAnhL0jUGbH441jkWjtoa/soZ2dEms5SwhGxrOBFNI2YrE4cw7BiLCpje9NNGEPR3uX2llrZk6Y4JvokcF6VCqFnp0RbJltsqpWvGorr+DjFmWYdSfn88RIcsvxbKy96tECJKA1Tdx97xKHnn3Prge8h1P121xV3RpywGBi8BuIVIm/QiaTLJ5vquTKCMxmlz/RhitvEZAj7eQ6bAFyfB3fQl1PStl2DrW3DZakeilrak+O/NGqiGRCdxk6aY7ATqg8Ibq4kqELPr5iLWCymv4mofo02tdvkYPXL9wMNffjGe+tSYaD3+XxnhBXJ/VvEO2X5baLUv6+TBXJ8NbNMbBgNbVSnX/0Ziu/EwumaFpfsrQB0bLcA2+oXC/jUW63XB07w0BfFRc6FwWVR7J3VRdjCmBPwOBUeEM7JLHa2vFcGpl3mx3VOqnXwLUxy0Q/+asWDSyMZTSfIFp/JL6dB/awyjNoUm1fLjlnvqwXneH0wLPSmzXSOxi11gGw8Tkc9lSoyTbW55iVm9dQF+PCYGk34i5bouh49qEuCCMmtJVFg3QEo6xp4Yp4vhk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
