travis:
  secure:
    BINSTAR_TOKEN: JLr3R47S1l3WREPzB0QN2wSzvDKNpl9n9cuksz4TVfjkdUW6UcM0d3wg3kEUJTvL9OmW1t690THIbN593yAXbDWryzR8pYNGzPJXTzKKKaVbxcu8esAnhL0jUGbH441jkWjtoa/soZ2dEms5SwhGxrOBFNI2YrE4cw7BiLCpje9NNGEPR3uX2llrZk6Y4JvokcF6VCqFnp0RbJltsqpWvGorr+DjFmWYdSfn88RIcsvxbKy96tECJKA1Tdx97xKHnn3Prge8h1P121xV3RpywGBi8BuIVIm/QiaTLJ5vquTKCMxmlz/RhitvEZAj7eQ6bAFyfB3fQl1PStl2DrW3DZakeilrak+O/NGqiGRCdxk6aY7ATqg8Ibq4kqELPr5iLWCymv4mofo02tdvkYPXL9wMNffjGe+tSYaD3+XxnhBXJ/VvEO2X5baLUv6+TBXJ8NbNMbBgNbVSnX/0Ziu/EwumaFpfsrQB0bLcA2+oXC/jUW63XB07w0BfFRc6FwWVR7J3VRdjCmBPwOBUeEM7JLHa2vFcGpl3mx3VOqnXwLUxy0Q/+asWDSyMZTSfIFp/JL6dB/awyjNoUm1fLjlnvqwXneH0wLPSmzXSOxi11gGw8Tkc9lSoyTbW55iVm9dQF+PCYGk34i5bouh49qEuCCMmtJVFg3QEo6xp4Yp4vhk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
