travis:
  secure:
    BINSTAR_TOKEN: 5zOqPvQZsMol/fp/uIrdo+y48RrH5QY41YVAYtb04XqL3MBk/etLnlWOV5IjLOp1XzMPCIDaIyNT8MzWGm40SQ/QePujkUjRwTUNhrhiWG0FeA40buvYyI4/Y3KnOytSy6c2Kc//K6GlxLt2QMWtoM6TTu+77xX8jaRTgbx1nD37MNaMTASXAiMMiRvJQt2hvv/5QdVIK0lNWYdOBtrh+bYOJzCuU75GmPqzibb08t52hJ2NH8ShPNUsWla+9BU3s7abPHY5/WVtdb0Ol4yEtFmaYQb78n/mHpllrv8cANIvQJuwYLNrZVKc+1oy41LHm/QS+EptZPTA1alHmxHTtQizUbBY4p0KyfdpzSR+BYE37IfxQAwkJBUDgSHLuSg7gkYze9AMZstKZIkovV/c7gohY/yfDYOfNhU3m67pGAREwJEiAgGn1Agey+VLvlJBy/axCE7B98f5rVoTCgIit6BQQ446aVagv+/nv1ewmOZ4XWFzg9dr+K6kVU463mH92b0yN+vlY7u2ZA75e74cCAcPL3i0Y6a548tOg9oZM6veLBOleIaiamtP+F5Cwl3UfUf8HXqh/opL/pyLvVRMQ/tn6n0LA+XjHpLFM5AvtI4m7TKcg+ePTCywVwugwgIZE0g578CXfdQPpE8fgPizho1zUjfJEX7YMya9GmWOm3s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
